site_name: Typhon
theme:
  name: "material"
  palette:
    primary: "brown"
    accent: "brown"
  sidebar:
    position: "left"

extra:
  social:
    - type: "github"
      link: "https://github.com/rednafi"
    - type: "twitter"
      link: "https://twitter.com/rednafi"
    - type: "linkedin"
      link: "https://www.linkedin.com/in/redowan"

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: true
  - toc:
      permalink: true
